// Package metadata contains the autogenerated telemetry and
// build information for the processor/datadogtags component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("datadogtags")
	ScopeName = "github.com/FLYR-Open-Source/datadogtagsprocessor"
)

const (
	TracesStability = component.StabilityLevelAlpha
	LogsStability   = component.StabilityLevelAlpha
)
